{% set data = load_setup_py_data() %}

package:
  name: biovis-base-plugins
  version: {{ data.version }}


source:
  - path: ../


build:
  include_recipe: True


requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - r-devtools
    - r-dplyr
    - r-shiny
    - r-plotly
    - r-ggpubr
    - r-rcolorbrewer
    - r-shinybs 
    - r-shinyjs
    - r-shinydashboard
    - r-ggvis
    - r-ggplot2
    - r-colourpicker
    - r-d3heatmap
    - r-shinycssloaders
    # Biovis Channel
    - r-scatterd3
    - r-ggcorrplot
    - r-upsetr
    - r-configr
    - r-biovis-reportr

# test:
#   imports:
#     - biovis_media_extension

about:
  home: {{ data.url }}
  license: MIT
  license_file: LICENSE.md
  license_family: MIT

  summary: {{ data.description }}
  description: {{ data.description }}
  doc_url: https://github.com/biovis-report/biovis-base-plugins/blob/master/README.md
  dev_url: {{ data.url }}